name: fish_redux
description: Fish Redux is an assembled flutter application framework based on Redux state management.
version: 0.1.7
author: Alibaba Xianyu Team <tino.wjf@alibaba-inc.com>
homepage: https://github.com/alibaba/fish-redux

environment:
    sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
    flutter_web: any
    flutter_web_ui: any

dev_dependencies:
    test: ^1.5.1
    
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # To add assets to your package, add an assets section, like this:
    # assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    #
    # For details regarding assets in packages, see
    # https://flutter.io/assets-and-images/#from-packages
    #
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.io/assets-and-images/#resolution-aware.
    # To add custom fonts to your package, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts in packages, see
    # https://flutter.io/custom-fonts/#from-packages
